[package]
name = "elastic-array"
version = "0.9.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
license = "MIT"
description = "Elastic vector backed by fixed size array"
repository = "https://github.com/debris/elastic-array"

[dependencies]
heapsize = "0.4"

[dev-dependencies]
rand = "0.3"
